config/routes.rb
Rad::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :works, only: [:show, :index] do
    collection do
      get "covers"
      get "poster"
      get "identity"
      get "random"
    end
  end

  root to: 'works#index'
  get 'info' => 'pages#info'
  get 'contact' => 'pages#contact'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :file, :position, :cover, :viewable
  has_attached_file :file, styles: {small: '240x240>', large: '600x600>'}
  validates_attachment :file, presence: true,
    content_type: { content_type: ['image/jpg', 'image/png', 'image/gif', 'image/jpeg'] }
  belongs_to :work
  



end

app/models/work.rb
class Work < ActiveRecord::Base
  has_many :images
  validates :name, presence: true
  attr_accessible :id, :name, :category, :detail, :order_work_by, :images_attributes, as: [:default, :admin] 
  accepts_nested_attributes_for :images, allow_destroy: true

# Previous and Next record
  def previous
  	Work.first(:conditions => ['id < ?', id], :order => "id desc")
	end

	def next
		Work.first(:conditions => ["id > ?", id], :order => "id asc")
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @works = Work.all
  end  

  def work
  end
  
  def info
  end
  
  def contact
  end

end

app/controllers/works_controller.rb
class WorksController < InheritedResources::Base
  def index
    @works = Work.all
    @images_cover = Image.order("images.id ASC").where(:cover => true)
  end
  def show
    @work = Work.find(params[:id])
    @cover = @work.images.where(:cover => true).first
  end
  def covers
    @works = Work.find(:all, :conditions => {:category => 'cover'}, :order => 'order_work_by')
    @images_cover = Image.order("images.id ASC").joins(:work).where('works.category' => 'cover')
    render :index
  end
  def poster
    @works = Work.find(:all, :conditions => {:category => 'poster'}, :order => 'order_work_by')
    render :index
  end
  def identity
    @works = Work.find(:all, :conditions => {:category => 'identity'}, :order => 'order_work_by')
    render :index
  end
  def random
    @works = Work.find(:all, :conditions => {:category => 'random'}, :order => 'order_work_by')
    render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Rad
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
	%body(data-spy="scroll" data-target="#navbar"){:id => "#{controller_name}", :class => "#{controller_name} #{controller_name}_#{action_name}"}
		#navbar.fixed-nav
			.row-fluid.loader-container
				#loader
				#simbols
			= link_to '', root_path, class: 'brand'
			%ul.nav
				%li.sub-section.works
					= link_to('work', works_path, class: 'work')
					%ul.nav.work-category
						%li
							= link_to 'covers', covers_works_path
						%li 
							= link_to 'poster', poster_works_path
						%li
							= link_to 'identity', identity_works_path
						%li
							= link_to 'random', random_works_path
				%li.pages_info
					= link_to('info', info_path, class: 'info')
				%li.pages_contact
					= link_to('contact', contact_path, class: 'contact')
		.no-margin.loader-section{:class => "#{action_name}"}
			= yield
	%script(type='text/javascript')
		QueryLoader.init();

app/views/pages/contact.html.haml
.row-fluid
	#contact
		.span4
			%h6 Artwork + Design
			%p Pilar Zeta
			= mail_to 'contact@radgency.com'
			%h6 Public Relationships + Press
			%p Carlitos Trujillo
			= mail_to 'carlitos@radgency.com'
			%h6 Marketing
			%p Bram Colaris
			= mail_to 'bram@radgency.com'
			%h6 Web Development
			%p Neeko Lalli
			= mail_to 'n@radgency.com'

app/views/pages/index.html.haml
.row-fluid#work
	- 9.times do
		= render 'gallery'

app/views/pages/info.html.haml
.row-fluid
	#info
		.span4
			%p RAD is a multidiciplinary boutique agency based in Berlin based in pure Magick. Founded and designed by artist <strong>Pilar Zeta</strong>.
			%h6 Begginings
			%p The universe RAD forms from the magical growth disc revolving around the young Sun. Their complex organic molecules are necessary for design and creativity life. It may have formed in the protoplanetary disk of dust grains, surrounding the Sun before the formation of it.
			%p According to the giant impact hypothesis, the moon is formed when RAD and Jupiter's moon Ganimide is formed, sending a very large number of moonlets into orbit which eventually coalesce to form the dark side of the Moon The gravitational pull of the new Moon stabilises the planet axis of rotation and sets up the conditions in which design life formed in the 11th dimension. In egyptian mitholgy RAD was worshiped by the sacred god Thoth as the galactic creativity chief sorcerer. RAD will help you to create your own Magic, reality.
		.span4
			%h6 Clients
			%p Universal Records - Hotflush - Big Beat  -STS9 - Supernature Records - Pulse Radio - Visionquest - Clown and Sunet - Wolf + Lamb - Fuse Brussels - Greco Roman - Mobilee Records - M-NUS - Unfokused - SAFE miami - Flying Circus - Crosstown Rebels - Club 4 Barcelona - Endless NYC - Floria Sigismondi - Foundry
			%h6 Nebula
			%p In NEBULA we create objects, lifestyle for the contemporary life. Check out our online store. 
			%h6 Services
			%p Magick. Graphic Design, Product Design, Packaging, Poster Art, Cover Art, Web Design, Fashion Design, Motion Graphics, Illustration, Dowsing.

app/views/works/_form.html.haml
= form_for @work do |f|
  - if @work.errors.any?
    #error_explanation
      %h2= "#{pluralize(@work.errors.count, "error")} prohibited this work from being saved:"
      %ul
        - @work.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/works/_gallery.html.haml
- @images_cover.each do |work|
  .span2
    = link_to({:action =>'show', :id => work.work_id }, :class => 'image') do
      - if image = work
        = image_tag(image.file.url(:large))
      .over
      .over_cross
        = image_tag('over_cross.png')

app/views/works/covers.html.haml
%h1 Hello Work!!

app/views/works/edit.html.haml
%h1 Editing work

= render 'form'

= link_to 'Show', @work
\|
= link_to 'Back', works_path

app/views/works/index.html.haml
.row-fluid#work
	- 9.times do
		= render 'gallery'

app/views/works/new.html.haml
%h1 New work

= render 'form'

= link_to 'Back', works_path

app/views/works/show.html.haml
.row-fluid
	.info
		.controls
			- if @work.previous
				= link_to('< Prev.', {:action =>'show', :id => @work.previous}, :class => 'prev') 
				%p - 
			- if @work.next
				= link_to('Next. >', {:action =>'show', :id => @work.next}, :class => 'next')
.row
	%ul.thumbnails
		-if @cover
			%li.span
				= image_tag(@cover.file.url(:large))
		-else
			%h3 NO COVER FOR THIS PROJECT.
	%p.detail #{@work.name} - #{@work.detail}
	%ul.thumbnails
		- @work.images.each do |image|
			%li.span
				= image_tag(image.file.url(:small))